version: '3'
services:
  
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/nginx/certs:ro
      - public:/usr/share/nginx/html
      - ./proxy:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx
    privileged: true
    volumes:
      - certs:/etc/nginx/certs:rw
      - public:/usr/share/nginx/html
      - ./proxy:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always

  mysql5:
    image: mysql:5.6
    container_name: mysql5
    ports:
      - '33065:3306'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql5/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always

networks:
  default:
    external:
      name: production

volumes:
  mysql:
    external: true
  mysql5:
    external: true
  certs:
  public:
