version: '3'
services:
  APP_NAME:
    image: ken109/laravel
    restart: always
    container_name: APP_NAME
    expose:
      - '80'
    environment:
      VIRTUAL_HOST: APP_NAME.DOMAIN
      LETSENCRYPT_HOST: APP_NAME.DOMAIN
      LETSENCRYPT_EMAIL: APP_MAIL
      LARAVEL_NAME: APP_NAME
      LARAVEL_ENV: production
      LARAVEL_DB_HOST: 172.18.0.1
      LARAVEL_DB_USER: sha2
      LARAVEL_DB_PASSWORD: password
      LARAVEL_DB_NAME: APP_NAME
      LARAVEL_DO_MIGRATION: "true"
    volumes:
      - .:/var/www/html

networks:
  default:
    external:
      name: production
